default_language_version.python = "3.13"

[[repos]]
repo = "https://github.com/pre-commit/pre-commit-hooks"
rev = "v6.0.0"
hooks = [{ id = "check-yaml" }, { id = "end-of-file-fixer" }]

[[repos]]
repo = "local"
hooks = [
  # Run the linter.
  { name = "ruff check", id = "ruff-check", entry = "uv run ruff check", language = "system", args = [
    "--fix",
  ], types_or = [
    "python",
    "pyi",
  ] },

  # Run the formatter.
  { name = "ruff format", id = "ruff-format", entry = "uv run ruff format", language = "system", types_or = [
    "python",
    "pyi",
  ] },
]
